spring:
  application:
    name: employee-api

  #Configuracion liquibase para la creacion de tablas
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    enabled: true

  #Configuracion h2 database
  datasource:
    url: jdbc:h2:mem:erpdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true 
      path: /h2-console #http://localhost:8080/h2-console
